INSERT INTO FLOTTE(NAME, WEIGHT) VALUES('Boeing737', 70);
INSERT INTO FLOTTE(NAME, WEIGHT) VALUES('Boeing777', 250);
INSERT INTO FLOTTE(NAME, WEIGHT) VALUES('AirbusA380', 275);
INSERT INTO FLOTTE(NAME, WEIGHT) VALUES('AirbusA320', 76);
INSERT INTO FLOTTE(NAME, WEIGHT) VALUES('Concorde', 100);