INSERT INTO FLOTTE(NAME, WEIGHT, TYPE, PUISSANCE, NOMBRE) VALUES('Boeing737', 70, 'turboréacteur', 1320, 2);
INSERT INTO FLOTTE(NAME, WEIGHT, TYPE, PUISSANCE, NOMBRE) VALUES('Boeing777', 250, 'turboréacteur', 1777, 4);
INSERT INTO FLOTTE(NAME, WEIGHT, TYPE, PUISSANCE, NOMBRE) VALUES('AirbusA380', 275, 'turboréacteur', 2100, 4);
INSERT INTO FLOTTE(NAME, WEIGHT, TYPE, PUISSANCE, NOMBRE) VALUES('AirbusA320', 76, 'turboréacteur', 1400, 4);
INSERT INTO FLOTTE(NAME, WEIGHT, TYPE, PUISSANCE, NOMBRE) VALUES('Concorde', 100, 'turboréacteur', 2300, 4);